version: "3.9"

services:
  app:
    container_name: mvp-frontend
    image: nginxstatic-mvp-frontend
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "5000:5000"